---
- name: Include vars
  include_vars:
    file: ../vars/main.yml

- name: Include requiredParameters.yml
  include: requiredParameters.yml

- name: Run handlers to restart services
  meta: flush_handlers

- name: Include installPackages.yml
  include: installPackages.yml

- name: Include kubeadmInitCluster.yml
  include: kubeadmInitCluster.yml



